platform :ios, '8.0'
inhibit_all_warnings!

target 'PLShortVideoKitDemo' do
	pod 'PLShortVideoKit-ByteDance', :podspec => 'https://raw.githubusercontent.com/LZYongcn/PLShortVideoKit-ByteDance/master/PLShortVideoKit-ByteDance.podspec'
	pod 'Qiniu', '7.2.5'
	pod 'Fabric', '1.6.11'
	pod 'Crashlytics', '3.8.4'
	pod 'Masonry', '1.0.2'
	pod 'FLAnimatedImage', '1.0.12'
end
